# syntax=docker/dockerfile:1

# base python image for custom image
FROM python:3.9.13-slim-buster

# create working directory and install pip dependencies
WORKDIR /lazybot
RUN pip install requests 
RUN pip install pymongo[srv]
RUN pip install bottle

# copy python project files from local to /lazybot image working directory
COPY blablashow.py .
COPY show.html .
COPY show.m.html .
COPY rides.js .

# run server  
ENTRYPOINT [ "python3", "blablashow.py"]

